/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Loading;

import blood_donation_project.MainFrame1;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Sushil Giri
 */
public class splasher extends javax.swing.JFrame {

    /**
     * Creates new form splasher
     */
    public splasher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Loading = new javax.swing.JLabel();
        LoadCompleted = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 3, 3)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loading.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        Loading.setText("Loading.............");
        jPanel2.add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 60));

        LoadCompleted.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        LoadCompleted.setText("Completed ");
        jPanel2.add(LoadCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 320, 40));
        jPanel2.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1020, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loading/blood-donation2.gif"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 490));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1020, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        splasher ob =new splasher();
        ob.setVisible(true);
        
        for(int i =0;i<=100;i++)
        {
            try
            {
                Thread.sleep(50);
                ob.Loading.setText(i+"%");
            if(i==10)
            {
                ob.LoadCompleted.setText("Turning on Modules.....");
            }
            else if(i==30)
            {
                ob.LoadCompleted.setText("Loading   Modules......");
            }
           else if(i==50)
            {
                ob.LoadCompleted.setText("Connecting to Databases.....");
            }
           else  if(i==70)
            {
                ob.LoadCompleted.setText("Connection Success..........");
            }
           else if(i==80)
            {
                ob.LoadCompleted.setText("Sever Fetching...... ");
            }
           else if(i==92)
            {
                ob.LoadCompleted.setText("Launching Application............");
            }
           ob.ProgressBar.setValue(i);
           
            
       
            }
            catch( Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LoadCompleted;
    public javax.swing.JLabel Loading;
    public javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
