/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DONOR;

import blood_donation_project.MainFrame1;
import blood_donation_project.editframe;
import dbdriver.Dbconnection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chavan Shreya Navnath
 */
public class View_details extends javax.swing.JFrame {
 Statement st=new Dbconnection().getConnection();
    /**
     * Creates new form View_details
     */
    public static String data[][];
    public View_details() {
        super("View_Details");
        initComponents();
        
        String colname []={"Adhar_Card ","Donor_name","Token_status"};
        View_donor_class ob=new View_donor_class();
        ob.getViewDonorDetails();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,colname));

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     VIEW DONOR DETAILS");
        jLabel1.setIconTextGap(18);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 750, 172));

        jTable1.setBackground(new java.awt.Color(0, 255, 255));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adhar_no", "Donor_name", "Token_status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 970, 440));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 220, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DONOR/Project_86-11.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1460, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(757, 757, 757))
        );

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu3.setForeground(new java.awt.Color(255, 51, 51));
        jMenu3.setText("Manage Profile");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu3.setMargin(new java.awt.Insets(0, 15, 0, 0));

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem2.setText("Edit Profile");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuItem2.setMargin(new java.awt.Insets(10, 35, 10, -1));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar6.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu4.setForeground(new java.awt.Color(255, 51, 51));
        jMenu4.setText("Donor");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu4.setIconTextGap(30);
        jMenu4.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem3.setText("Add New Donor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem4.setText("View Details");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar6.add(jMenu4);

        jMenu8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu8.setForeground(new java.awt.Color(255, 51, 51));
        jMenu8.setText("Logout");
        jMenu8.setAlignmentX(2.0F);
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu8.setIconTextGap(30);

        jMenuItem9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jMenuItem9.setText("Exit");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuBar6.add(jMenu8);

        setJMenuBar(jMenuBar6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        editframe er =new editframe();
        Dimension ob =java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        er.setVisible(true);
        er.setSize(ob);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        Donor_register12 op = new Donor_register12();
        Dimension ob =Toolkit.getDefaultToolkit().getScreenSize();
        op.setVisible(true);
        op.setSize(ob);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.dispose();        
        MainFrame1 l=new MainFrame1();
        Dimension ob =Toolkit.getDefaultToolkit().getScreenSize();
        l.setVisible(true);
        l.setSize(ob);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         this.dispose();
        View_details er =new View_details();
        Dimension ob =java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        er.setVisible(true);
        er.setSize(ob);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int row = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        if (jTable1.getSelectedRowCount() == 1) {
            String aadhar = (String) model.getValueAt(row, 0);
            String name = (String) model.getValueAt(row, 1);

            // Assuming the Dbconnection and Donor_Data_fetcher_edit classes work correctly.
            Statement st = new Dbconnection().getConnection();
            ArrayList data = new Donor_Data_fetcher_edit().getDonordata(st, aadhar);

            this.dispose();
            Edit_donor eddf = new Edit_donor();
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            eddf.setVisible(true);
            eddf.setSize(d);

            eddf.jTextField1.setText(aadhar);
            eddf.jTextField8.setText((String) data.get(0));
            eddf.jTextField9.setText((String) data.get(1));
            eddf.jTextField10.setText((String) data.get(2));
            eddf.jTextArea1.setText((String) data.get(3));

            String Gender = (String)data.get(6); // Assuming Gender is fetched from the data.
            if (Gender.equals("Male"))
            eddf.jRadioButton1.setSelected(true);
            if (Gender.equals("Female"))
            eddf.jRadioButton2.setSelected(true);
            if (Gender.equals("Other"))
            eddf.jRadioButton3.setSelected(true);

            // Assuming Dob is fetched from the data.
            String Dob = (String)data.get(4);
            String str[] = Dob.split("/");
            String D = str[0];
            String M = str[1];
            String Y = str[2];
            eddf.jComboBox2.setSelectedItem(D);
            eddf.jComboBox3.setSelectedItem(M);
            eddf.jComboBox4.setSelectedItem(Y);
            eddf.jComboBox1.setSelectedItem((String)data.get(9));
            // Assuming other data is fetched from the data ArrayList.
            eddf.jTextField2.setText((String)  data.get(7));
            eddf.jTextField4.setText((String)  data.get(8));
            eddf.jTextField6.setText((String)  data.get(5));
            eddf.jTextField7.setText((String)  data.get(10));
            eddf.jTextField13.setText((String) data.get(11));
            eddf.jTextField15.setText((String) data.get(12));
            eddf.jTextField14.setText((String) data.get(13));
            eddf.jTextField3.setText((String)  data. get(14));

            //                String Name=rs.getString(2);
            //                String Mobile=rs.getString(3);
            //                String Email=rs.getString(4);
            //                String Address=rs.getString(5);
            //                String DOB=rs.getString(6);
            //                String Age=rs.getString(7);
            //                String Gender=rs.getString(8);
            //                String Height=rs.getString(9);
            //                String Weight=rs.getString(10);
            //                String BloodG=rs.getString(11);
            //                String BMI=rs.getString(12);
            //                String Token=rs.getString(13);
            //                String Token_status=rs.getString(14);
            //                String Date_time=rs.getString(15);
            //                String Blood_v=rs.getString(16);
            //
        }
        else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "TABLE IS EMPTY");
            } else {
                JOptionPane.showMessageDialog(null, "Row not Selected,Select One Row");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
